repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version (keep in sync with the version in pyproject.toml)
  rev: v0.7.3
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
