repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version (keep in sync with the version in pyproject.toml)
  rev: v0.11.0
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format

- repo: https://github.com/pre-commit/mirrors-mypy
  # MyPy version (keep in sync with the version in pyproject.toml)
  rev: v1.15.0  
  hooks:
    - id: mypy
      additional_dependencies: ['types-tabulate']
      args: [--config-file=pyproject.toml]
      pass_filenames: true
      stages: [pre-commit]
