version: 2

build:
  os: ubuntu-22.04 # A stable LTS release
  tools:
    python: "3.13" # Using 3.13 as per your project's choice

  commands:
    # 1. Install Poetry itself into the Read the Docs virtual environment.
    - python -m pip install poetry

    # 2. Install your project's dependencies, including the 'docs' extra.
    #    Poetry is smart enough to detect the active virtual environment created by RTD
    #    and will install dependencies into it.
    - poetry install --extras docs

    # 3. Build the Sphinx documentation using 'poetry run'.
    #    Adjust 'docs/source' to your actual Sphinx source directory.
    - poetry run sphinx-build -T -b html -d _build/doctrees -D language=en docs/source $READTHEDOCS_OUTPUT/html

# New section to explicitly handle Git submodules
# Read the Docs will automatically clone and update these.
submodules:
  include: all # This tells RTD to process all submodules defined in your .gitmodules file.
  # If you only had specific submodules needed for docs, you could list them like:
  # include:
  #   - submodules/qiskit-device-benchmarking
  # depth: 1 # Optional: speeds up cloning by only fetching the latest commit for submodules too

# You can keep the sphinx block for clarity, but 'commands' will take precedence.
sphinx:
  configuration: docs/source/conf.py

# Other optional configurations
formats: all