version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.13"

  commands:
    # --- 1. Clone, Build, and Install Qrack C++ Library from Source ---
    # Moved apt-get installs to the dedicated 'apt' section below.

    - git clone https://github.com/unitaryfoundation/qrack.git /tmp/qrack_cpp_src
    - cd /tmp/qrack_cpp_src
    - mkdir build && cd build
    - cmake ..
    - make install # This should now work as system packages are installed by 'apt:' block

    - cd $READTHEDOCS_ROOT

    # --- 2. Install Poetry and Python Dependencies ---
    - python -m pip install poetry
    - poetry install --extras docs

    # --- 3. Build Sphinx Documentation ---
    - poetry run sphinx-build -T -b html -d _build/doctrees -D language=en docs/source $READTHEDOCS_OUTPUT/html

# NEW: Dedicated 'apt' section for system packages
apt:
  packages:
    - cmake
    - build-essential
    - ocl-icd-opencl-dev
    - opencl-headers

submodules:
  include: all

sphinx:
  configuration: docs/source/conf.py
  builder: html
  fail_on_warning: false

formats: all