version: 2

submodules:
  include: all

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .

sphinx:
   configuration: docs/source/conf.py
