version: 2

build:
  os: ubuntu-22.04 # Use a stable LTS release for Read the Docs builds
  tools:
    python: "3.13" # Ensure this matches or is compatible with your pyproject.toml's python version.

  commands:
    # --- 1. Install System Build Dependencies & OpenCL ---
    # Update package lists to ensure we can install the latest versions of dependencies.
    - apt-get update # REMOVED sudo
    # Install essential tools for compiling C++ projects (cmake, build-essential which includes g++)
    # and OpenCL development libraries (ocl-icd-opencl-dev provides libOpenCL.so.1).
    - apt-get install -y cmake build-essential ocl-icd-opencl-dev opencl-headers # REMOVED sudo

    # --- 2. Clone, Build, and Install Qrack C++ Library from Source ---
    # The 'make install' step is crucial as it places libqrack_pinvoke.so in a system-wide path.

    # Clone the Qrack C++ repository into a temporary directory.
    - git clone https://github.com/unitaryfoundation/qrack.git /tmp/qrack_cpp_src

    # Navigate into the cloned Qrack source directory.
    - cd /tmp/qrack_cpp_src
    # Create a build directory and move into it (standard CMake practice).
    - mkdir build && cd build
    # Configure the Qrack project build using CMake.
    - cmake ..
    # Compile and install Qrack. 'make install' places the compiled shared library
    # (libqrack_pinvoke.so) into standard system library paths (e.g., /usr/local/lib).
    - make install # REMOVED sudo

    # Return to the main project's root directory.
    - cd $READTHEDOCS_ROOT

    # --- 3. Install Poetry and Python Dependencies ---
    - python -m pip install poetry
    - poetry install --extras docs

    # --- 4. Build Sphinx Documentation ---
    - poetry run sphinx-build -T -b html -d _build/doctrees -D language=en docs/source $READTHEDOCS_OUTPUT/html

submodules:
  include: all

sphinx:
  configuration: docs/source/conf.py
  builder: html
  fail_on_warning: false

formats: all