version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.13"

  commands:
    - pip install poetry
    - poetry config virtualenvs.in-project true
    - poetry install --no-root --with dev
    - make html # THIS MUST BE CALLED FROM THE ROOT

python:
  install:
    - method: pip
      path: .

sphinx:
  configuration: docs/source/conf.py # This is good practice to keep for clarity/validation
  builder: html
  fail_on_warning: false