version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

sphinx:
   configuration: docs/source/conf.py

# Add this install section
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev # If you need development dependencies for your docs build
