version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.13"

  commands:
    # Install Poetry itself using pip
    - pip install poetry

    # Configure Poetry to create virtualenvs inside the project directory
    - poetry config virtualenvs.in-project true

    # Use Poetry to install all your project dependencies, including dev dependencies.
    - poetry install --no-root --with dev

    # Navigate into the docs/source directory before running make html
    # This ensures Sphinx generates output relative to docs/source
    - cd docs/source

    # Run the make html command to build the documentation
    # By default, Sphinx will put the output in ./_build/html relative to the current dir (docs/source)
    - make html

python:
  install:
    - method: pip
      path: .

sphinx:
  configuration: docs/source/conf.py # This confirms your conf.py location
  builder: html
  fail_on_warning: false