version: 2

build:
  os: ubuntu-22.04 # Use 'ubuntu-22.04' as 'ubuntu-24.04' might not be fully supported yet or is causing issues.
                  # Read the Docs often lags a bit behind new Ubuntu releases.
  tools:
    python: "3.13"

  commands:
    # Install Poetry itself using pip
    - pip install poetry

    # Configure Poetry to create virtualenvs inside the project directory
    # This makes it easier for subsequent steps to find dependencies
    - poetry config virtualenvs.in-project true

    # Use Poetry to install all your project dependencies, including dev dependencies.
    - poetry install --no-root --with dev

python:
  install:
    # Use 'pip' as the method, but then run Poetry commands manually
    - method: pip
      path: .
      # No 'requirements.txt' needed here as Poetry handles it in 'build.commands'


sphinx:
  configuration: docs/source/conf.py
  builder: html
  fail_on_warning: false