name: Publish Python Package to TestPyPI

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  distributions:
    if: github.event.release.prerelease == true
    uses: ./.github/workflows/distribution-test.yml
    with:
      release-tag: ${{ github.event.release.tag_name }}

  publish:
    needs: distributions
    name: Publish tested distributions to TestPyPI
    runs-on: ubuntu-latest
    environment: testpypi
    permissions:
      id-token: write  # This is required for trusted publishing

    steps:
      - name: Download tested distributions
        uses: actions/download-artifact@v8
        with:
          name: python-distributions
          path: dist

      - name: Publish package distributions to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
