name: Publish Python Package to PyPI

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  distributions:
    if: github.event.release.prerelease == false
    uses: ./.github/workflows/distribution-test.yml
    with:
      release-tag: ${{ github.event.release.tag_name }}

  publish:
    needs: distributions
    name: Publish tested distributions to PyPI
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write  # This is required for trusted publishing

    steps:
      - name: Download tested distributions
        uses: actions/download-artifact@v8
        with:
          name: python-distributions
          path: dist

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
